<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>arpeggio</AssemblyName>
    <RootNamespace>Arpeggio.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arpeggio.Codecs\Arpeggio.Codecs.csproj" />
    <ProjectReference Include="..\Arpeggio.Core\Arpeggio.Core.csproj" />
  </ItemGroup>

</Project>
